syntax = "proto3";

package spx.messages;

message PreVoteRequest {
    // The ID of the pre-candidate who sent the pre-vote message
    string member_id = 1;

    // The next term (ballot) number the pre-candidate proposing to start
    uint32 next_term = 2;

    // The term number of the last log entry persisted by the pre-candidate
    uint32 last_log_term = 4;

    // The slot number of the last log entry persisted by the pre-candidate
    uint32 last_log_slot = 3;
}

message PreVoteResponse {
    // The ID of the member who responded to the pre-vote message
    string member_id = 2;

    // The receiver's current term is always required, regardless of the outcome
    uint32 term = 1;

    // A flag indicating whether the member has granted a vote for the pre-candidate
    bool vote_granted = 3;

    // Tells the Candidate to abort the election because this leader's TrueTime lease is still active.
    optional string current_leader_id = 4;

    // Provides a catch-up hint telling the Candidate that it could be saving logs with the wrong term,
    // and would need to delete its stale uncommitted entries
    optional uint32 member_last_log_term = 5;

    // Provides a catch-up hint telling the Candidate how far behind its logs are compared to this Follower.
    optional uint32 member_last_log_slot = 6;
}
