syntax = "proto3";

package spx.services;

import "messages/accept.proto";
import "messages/client_write.proto";
import "messages/pre_vote.proto";
import "messages/vote.proto";

service Paxos {
  // Sent by an external client to submit a write to the leader
  rpc ClientWrite (messages.ClientWriteRequest) returns (messages.ClientWriteResponse);

  // Sent by leader pre-candidate to grant votes from members to become a leader candidate
  rpc PreVote (messages.PreVoteRequest) returns (messages.PreVoteResponse);

  // Sent by leader candidate to grant votes from members to become a leader
  rpc RequestVote (messages.RequestVoteRequest) returns (messages.RequestVoteResponse);

  // Sent by leader to replicate log entries and advance the commit index on followers
  rpc Accept (messages.AcceptRequest) returns (messages.AcceptResponse);
}